--- #YAML:1.0
name:               MogileFS-Utils
version:            2.19
abstract:           MogileFS utilities
author:
    - Brad Fitzpatrick <brad@danga.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::Zlib:    0
    LWP::Simple:       0
    MogileFS::Client:  1.14
resources:
    bugtracker:   http://code.google.com/p/mogilefs/issues/list
    homepage:     http://www.mogilefs.org
    MailingList:  http://groups.google.com/group/mogile
    repository:   git://github.com/mogilefs/MogileFS-Utils.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
