# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MogileFS-Utils
version:      2.10
version_from: 
installdirs:  site
requires:
    Compress::Zlib:                0
    LWP::Simple:                   0
    MogileFS::Client:              1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
